# Generated by Django 4.1.6 on 2023-03-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='statuses',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='types',
        ),
    ]
