# Generated by Django 4.1.6 on 2023-03-21 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0002_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('manage_project_users', 'Редактировать пользователей проекта')]},
        ),
    ]
