# Generated by Django 4.1.6 on 2023-03-21 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('create_project_users', 'Создовать пользователей проекта'), ('delete_project_users', 'Удалять пользователей проекта')]},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('create_project_tasks', 'Создовать задачи проекта'), ('update_project_tasks', 'Редактировать задачи проекта'), ('delete_project_tasks', 'Удалять задачи проекта')]},
        ),
    ]
